version: "3"
services:
  postgres:
    image: postgres:13-bullseye
    ports:
      - 5432
    environment:
      - POSTGRES_DB=pbsportal
      - POSTGRES_USER=pbsportal
      - POSTGRES_PASSWORD=pbsportal
  postgres-test:
    image: postgres:13-bullseye
    ports:
      - 5432
    environment:
      - POSTGRES_DB=pbsportal-test
      - POSTGRES_USER=pbsportal-test
      - POSTGRES_PASSWORD=pbsportal-test
  selenium:
    image: docker-registry.itds.ch/selenium/standalone-firefox:4.6.0
    ports:
      - 4444
    environment:
      SE_SCREEN_WIDTH: 2970
      SE_SCREEN_HEIGHT: 1160
      SE_VNC_NO_PASSWORD: 1
      SE_NODE_OVERRIDE_MAX_SESSIONS: true
      SE_NODE_MAX_SESSIONS: 5
    volumes:
      - "/dev/shm:/dev/shm"
