version: "3"
services:
  postgres:
    image: postgres:13
    ports:
      - 5432
    environment:
      - POSTGRES_DB=pbsportal
      - POSTGRES_USER=pbsportal
      - POSTGRES_PASSWORD=pbsportal
  postgres-test:
    image: postgres:13
    ports:
      - 5432
    environment:
      - POSTGRES_DB=pbsportal-test
      - POSTGRES_USER=pbsportal-test
      - POSTGRES_PASSWORD=pbsportal-test
  selenium-firefox:
    image: docker-registry.itds.ch/selenium/standalone-firefox:4.6.0
    ports:
      - 4444
    environment:
      SCREEN_WIDTH: 2970
      SCREEN_HEIGHT: 1160
      SE_VNC_NO_PASSWORD: 1
    volumes:
      - "/dev/shm:/dev/shm"
