bootstrap:
  data:
    midataGroups:
      - name: Pfadibewegung Schweiz
        midata-id: 1
    categories: # categories are referenced by name
      - name:
          de: Hauptkategorie
          fr: Hauptkategorie
          it: Hauptkategorie
          en: Hauptkategorie
      - name:
          de: Lager & Kurse
          fr: Lager & Kurse
          it: Lager & Kurse
          en: Lager & Kurse
    masterTiles: # tiles are referenced by title.de (if available) or title.en (as fallback)
      - title:
          de: MiData DE
          fr: MiData FR
          it: MiData IT
          en: MiData EN
        content:
          de: MiData Content DE
          fr: MiData Content FR
          it: MiData Content IT
          en: MiData Content EN
        category:
          name:
            de: Hauptkategorie
        position: 1
        enabled: true
        titleColor: DEFAULT
        apiKey: DEMO-KEY
        midata-group-only:
          midata-id: 1
      - title:
          de: Lagerkochbuch DE
          fr: Lagerkochbuch FR
          it: Lagerkochbuch IT
          en: Lagerkochbuch EN
        content:
          de: Lagerkochbuch Content DE
          fr: Lagerkochbuch Content FR
          it: Lagerkochbuch Content IT
          en: Lagerkochbuch Content EN
        url:
          de: https://www.lagerkochbuch.ch
          fr: https://www.lagerkochbuch.ch
          it: https://www.lagerkochbuch.ch
          en: https://www.lagerkochbuch.ch
        category:
          name:
            de: Lager & Kurse
        position: 2
        enabled: true
        titleColor: DEFAULT
        midata-group-only:
          midata-id: 1
      - title:
          en: EN-Only
        content:
          en: EN-Only Content
        category:
          name:
            de: Hauptkategorie
        position: 3
        enabled: true
        titleColor: DEFAULT
        apiKey: DEMO-KEY-EN-ONLY
        midata-group-only:
          midata-id: 1
